### ISSUE TITLE
games-emulation/libretro-meta-9999-r16 : typo in RDEPEND causing ebuild to fail

### ISSUE THREAD

**Issue by jeandestouches** [Menelkir/gentoo-overlay#1]
Hi,
At line 71,

mednafen-bses? ( games-emulation/mednafen-bsnes-libretro )

should be

mednafen-bsnes? ( games-emulation/mednafen-bsnes-libretro )

Thank you very much for your overlay by the way!

Cheers

EDIT :

https://gitlab.com/menelkir/gentoo-overlay/-/blob/master/games-emulation/libretro-meta/libretro-meta-9999-r16.ebuild

**Comment by Menelkir** [comment]
Fixed and bumped libretro-meta version, thanks.
